import Head from 'next/head';
import Link from 'next/link'
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Layout() {
    return (
        <div>
            <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <h1 className={styles.title}>
            Mira
          </h1>
          <div className={styles.grid}>
            <Link href='/server' className={styles.card}>
             <a><h2>Server</h2></a> 
            </Link>

            <Link href='/channels' className={styles.card}>
              <a><h2>Channels </h2></a>
            </Link>

            <Link href='/users' className={styles.card}>
              <a><h2>Users </h2></a>
            </Link>

            <Link href='/user/[userId]' className={styles.card}>
             <a><h2>Me </h2></a> 
            </Link>
          </div>
        </nav>
      </header>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
        </div>
    )
}